# Generated by Django 3.1.3 on 2021-02-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinglot',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
