# Generated by Django 3.1.3 on 2021-03-09 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_settings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='Setting',
        ),
    ]
